# Classical Mechanics I (PHYS 311)
## Studio 13

*Name:* Nathan Whittington

*Date:* 11/21/25

## Matrix Operations

In [3]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


Google how to represent matrices in numpy. If any of the following bolded terms are unfamiliar to you, google them! Wikipedia is your friend.

* Create a 3x3 matrix A.
* Demonstrate how to multiply that matrix by a scalar.
* Demonstrate multiplying A by a different 3x3 matrix. (This is not with the `*` operator!)
* Multiply A by a (3D) vector. (i.e. calculate Av)
* Calculate the **transpose** of A.
* Calculate the **trace** of A.
* Calculate the **determinant** of A.
* Calculate the **inverse** of A if it exists.
* Create a 3-vector with nonzero x,y,z components, and rotate it about the x axis by an angle $pi/2$. Look up the form of a 3D rotation matrix.
* EC(+0.5): Demonstrate a nonzero rotation of a 10-dimensional vector $\vec{v}=(x_1,x_2,...,x_10)$ in the $x_1,x_2$ plane



In [21]:
A = np.array([[1,2,3],[2,4,8],[3,8,5]])
B = np.array([[5,4,2],[2,3,4],[1,5,7]])
print("A =", A, "\n")
print("B =", B, "\n")
print("v =", v:=np.array([1,2,3]), "\n")
print("A*5 =", A*5, "\n")
print("A*B =", A @ B, "\n")
print("Av =", np.dot(A,v), "\n")
print(f"A.T = {A.T}\n")
print(f"trace(A) = {np.trace(A)}\n")
print(f"det(A) = {np.linalg.det(A)}\n")
print(f"A^-1 = {np.linalg.inv(A)}\n")
print(f"v rot 90 = {np.dot(np.array([[1,0,0],[0,np.cos(np.pi/2), -np.sin(np.pi/2)], [0, np.sin(np.pi/2), np.cos(np.pi/2)]]),v)})\n")
w = [1,2,3,4,5,6,7,8,9,10]
rot10 = np.eye(10)
rot10[0][0] = np.cos(np.pi/4)
rot10[0][1] = -np.sin(np.pi/4)
rot10[1][0] = np.sin(np.pi/4)
rot10[1][1] = np.cos(np.pi/4)
print(f"w = {w}\n")
print(f"w rot 45 in x1,x2 plane = {np.dot(rot10,w)}\n")



A = [[1 2 3]
 [2 4 8]
 [3 8 5]] 

B = [[5 4 2]
 [2 3 4]
 [1 5 7]] 

v = [1 2 3] 

A*5 = [[ 5 10 15]
 [10 20 40]
 [15 40 25]] 

A*B = [[12 25 31]
 [26 60 76]
 [36 61 73]] 

Av = [14 34 34] 

A.T = [[1 2 3]
 [2 4 8]
 [3 8 5]]

trace(A) = 10

det(A) = -3.999999999999999

A^-1 = [[11.  -3.5 -1. ]
 [-3.5  1.   0.5]
 [-1.   0.5 -0. ]]

v rot 90 = [ 1. -3.  2.])

w = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

w rot 45 in x1,x2 plane = [-0.70710678  2.12132034  3.          4.          5.          6.
  7.          8.          9.         10.        ]



Google how to find the eigenvectors of matrices in numpy.

* Calculate a moment of inertia tensor for a system of two particles with equal mass (let's set it to 1). One at the origin, and the other at (1,1,0).
* Find the eigenvectors of this new moment of inertia tensor. (Comment on the resulting eigenvectors!) Notice that numpy will return normalized eigenvectors.
* EC(+0.5): Now that you have the eigenvectors, you can express your system in a coordinate system defined by these three eigenvectors. Calculate the the second particle position in this new coordinate system. (Remember that the $x^\prime$ component of a vector $\vec{v}$ will just be $\vec{v}\cdot\hat{x}^{\prime}$.) You should have new descriptions of the two particle positions in this new basis. Calculate the moment of inertia tensor in this new coordinate system and show that it's diagonal! i.e. the Eigenvectors of the matrix are the principle axes!

In [60]:
r1 = np.array([[0],[0],[0]])
r2 = np.array([[1],[1],[0]])
m = 1
I3 = np.eye(3)

I = m*((r1.T @ r1) * I3 + (r2.T @ r2) * I3 - r1 @ r1.T - r2 @ r2.T)
print(f"I = {I}\n")
eigvals, eigvecs = np.linalg.eigh(I)
print(f"Eigen Vals = {eigvals}\nEigen Vectors = \n{eigvecs}\n")
s1 = (eigvecs @ r1)
s2 = (eigvecs @ r2)

print(f'r1\' = {s1}\n')
print(f'r2\' = {s2}\n')

J = m*((s1.T @ s1) * I3 + (s2.T @ s2) * I3 - s1 @ s1.T - s2 @ s2.T)
print(f"New moment of inertia Tensor = \n{J}")

I = [[ 1. -1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  2.]]

Eigen Vals = [0. 2. 2.]
Eigen Vectors = 
[[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [-0.          0.          1.        ]]

r1' = [[0.]
 [0.]
 [0.]]

r2' = [[-1.41421356]
 [ 0.        ]
 [ 0.        ]]

New moment of inertia Tensor = 
[[0. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


Since I is symmetric, the eigenvalues will be orthagonal, creating an eigen basis. The new Moment of Inertia tensor is now diagonal.