# Classical Mechanics I (PHYS 311)
## Studio 14

*Name:* Nathan Whittington

*Date:* 12/1/2025

## Matrix Operations

In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Google how to find the eigenvectors of matrices in numpy.

1. Create a (3x3) diagonal matrix, and find its eigenvectors. Make sure it's not the identity matrix.
2. Do the same for a non-diagonal 3x3 matrix.
3. Calculate a moment of inertia tensor for a system of two particles with equal mass (let's set it to 1). One at the origin, and the other at (1,1,0).
4. Find the eigenvectors of this new moment of inertia tensor. (Comment on the resulting eigenvectors!) Notice that numpy will return normalized eigen vectors.
5. Now that you have the eigenvectors, you can express your system in a coordinate system defined by these three eigenvectors. Calculate the representation of the second particle position in this new coordinate system. (Remember that the $x^\prime$ value of a vector $\vec{v}$ will just be $\vec{v}\cdot\hat{x}^{\prime}$.) You should have new descriptions of the two particle positions in this new basis.
6. Calculate the moment of inertia tensor in this new coordinate system and show that it's diagonal! i.e. the Eigenvectors of the matrix are the principle axes!

7. EC(+0.5): Use some 3D axes to draw the above operations (starting from the two-particle system). Draw the two particles in the original basis. Draw the eigenvectors of the inertia tensor and show how this process is aligning the axes to the symmetry axes of the system.

In [29]:
A = np.array([[5,0,0],[0,-2,0],[0,0,3]])
Aval, Avec = np.linalg.eigh(A)
print(f"Diagonal 3x3 =\n{A}\nEigenvectors =\n{Avec}\n")
B = np.array([[1,2,3],[3,2,1],[5,4,3]])
Bval, Bvec = np.linalg.eigh(B)
print(f"Non-Diagonal 3x3 =\n{B}\nEigenvectors =\n{Bvec}\n")


m = 1
r1 = (0,0,0)
r2 = (1,1,0)

def get_I(p, m):
  x, y, z = p

  return m * np.array([
              [y*y + z*z,   -x*y,        -x*z],
              [-x*y,        x*x + z*z,   -y*z],
              [-x*z,        -y*z,        x*x + y*y]
          ])

I = get_I(r1, m) + get_I(r2, m)
eigvals, eigvecs = np.linalg.eigh(I)

print(f"Inertia Tensor for a two particles at (0,0,0) and (1,1,0) =\n{I}")
print(f"Inertia Tensor's Eigenvalues =\n{eigvecs}")
print("\nThe Eigenvectors of the Inertia Tensor are symmetric and orthonormal")

r1_prime = eigvecs.T @ r1
r2_prime = eigvecs.T @ r2
print(f"{r1} --> {r1_prime}\n{r2} --> {r2_prime}\n")

I_prime = get_I(r1_prime, m) + get_I(r2_prime, m)
print(f"Inertia tensor in the new eigen basis coordinate system =\n{I_prime}")
print('The resulting matrix is indeed diagonal')

Diagonal 3x3 =
[[ 5  0  0]
 [ 0 -2  0]
 [ 0  0  3]]
Eigenvectors =
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Non-Diagonal 3x3 =
[[1 2 3]
 [3 2 1]
 [5 4 3]]
Eigenvectors =
[[ 0.74529991  0.39917153 -0.53403196]
 [ 0.08043442 -0.84895366 -0.52231024]
 [-0.66185976  0.34632323 -0.66483222]]

Inertia Tensor for a two particles at (0,0,0) and (1,1,0) =
[[ 1 -1  0]
 [-1  1  0]
 [ 0  0  2]]
Inertia Tensor's Eigenvalues =
[[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [-0.          0.          1.        ]]

The Eigenvectors of the Inertia Tensor are symmetric and orthonormal
(0, 0, 0) --> [0. 0. 0.]
(1, 1, 0) --> [-1.41421356  0.          0.        ]

Inertia tensor in the new eigen basis coordinate system =
[[ 0.  0.  0.]
 [ 0.  2. -0.]
 [ 0. -0.  2.]]
The resulting matrix is indeed diagonal
